services:
  fcp-mpdp-frontend:
    build:
      context: .
      target: development
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    environment:
      MPDP_BACKEND_ENDPOINT: ${MPDP_BACKEND_ENDPOINT:-http://fcp-mpdp-backend:3001}
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY}
