services:
  development:
    container_name: fcp-mpdp-frontend-development
    build: ./
    ports:
      - '3000:3000'
    links:
      - 'localstack:localstack'
    depends_on:
      localstack:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://fcp-mpdp-frontend-localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - fcp-mpdp
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  localstack:
    image: localstack/localstack:3.0.2
    container_name: fcp-mpdp-frontend-localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - fcp-mpdp

networks:
  fcp-mpdp:
    driver: bridge
    name: fcp-mpdp
