services:
  fcp-mpdp-frontend:
    build:
      target: development
    command: npm test
    environment:
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY_TEST}
    volumes:
      - ./test:/home/node/test
      - ./coverage:/home/node/coverage
